# -*- makefile -*-
#
# Configuration for Apple Silicon macOS with Homebrew
#

# SYSTEM FOR INSTALLATION

SYSTEM_TYPE = brew

# Homebrew prefix on Apple Silicon
HOMEBREW_PREFIX = /opt/homebrew

# If LATEX_FREE is set, the only thing that will change is that when launching
# AMC, it will check if you have latex and that automultiplechoice.sty is
# reachable.
LATEX_FREE = 1

# The PERLPATH must be Homebrew's Perl
PERLPATH = $(HOMEBREW_PREFIX)/opt/perl/bin/perl

# This variable allows us to tell where the opencv and netpbm libraries are.
LIBS_PREFIX = $(HOMEBREW_PREFIX)

CFLAGS = -O2 -I$(LIBS_PREFIX)/include -I. -DNEEDS_GETLINE
CXXFLAGS = -O2 -I$(LIBS_PREFIX)/include -I. -DNEEDS_GETLINE
LDFLAGS += -L$(LIBS_PREFIX)/lib

# INSTALLATION : where to install parts of the package ?

ifndef PREFIX
PREFIX = $(HOMEBREW_PREFIX)
endif

# directory for executable
BINDIR=$(PREFIX)/bin
# directory for perl modules
PERLDIR=$(PREFIX)/libexec/lib/perl5
# directory for some AMC executables, not to be used by end-user
MODSDIR=$(PREFIX)/lib/AMC
# directory for LaTeX style file
TEXDIR=$(PREFIX)/share/texmf-local/tex/latex/AMC
# directory for LaTeX doc
TEXDOCDIR=$(PREFIX)/share/texmf-local/doc/latex/AMC/
# directory for man (1) files
MAN1DIR=$(PREFIX)/share/man/man1
# directory for desktop file
DESKTOPDIR=
# directory for icons (svg)
ICONSDIR=$(PREFIX)/share/auto-multiple-choice/icons
# directory for the main (svg) icon
APPICONDIR=
# directory for icons (xpm)
PIXDIR=
# directory for locales (MO files will be put in
#                        $(LOCALEDIR)/fr/LC_MESSAGES for example)
LOCALEDIR=$(PREFIX)/share/locale
# directory for AMC packaged models
MODELSDIR=$(PREFIX)/share/auto-multiple-choice/models
# directory for documentation (will use html/auto-multiple-choice.* subdirs for HTML docs)
DOCDIR=$(PREFIX)/share/doc/auto-multiple-choice

# No syntax highlighting for gedit
SHARED_MIMEINFO_DIR=
LANG_GTKSOURCEVIEW_DIR=

# BUILD : where to find some files used for building AMC ?
# URLs can be used if XML catalogs are present.

DOCBOOK_MAN_XSL = $(HOMEBREW_PREFIX)/opt/docbook-xsl/docbook-xsl/manpages/docbook.xsl
DOCBOOK_XHTML_XSL = $(HOMEBREW_PREFIX)/opt/docbook-xsl/docbook-xsl/xhtml/chunk.xsl
DOCBOOK_DTD = $(HOMEBREW_PREFIX)/opt/docbook/docbook/xml/4.5/docbookx.dtd

# BUILD : options to compile with opencv libraries

GCC_OPENCV = -I$(LIBS_PREFIX)/include/opencv4
GCC_OPENCV_LIBS = -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs

# BUILD : options to compile with poppler glib libraries
GCC_PDF = $(shell pkg-config --cflags --libs cairo pangocairo poppler-glib)
GCC_POPPLER = $(shell pkg-config --cflags --libs poppler-glib gio-2.0)

# INFO IN DESKTOP FILE

DESKTOP_CAT=Education;

# INSTALL USER AND GROUP

INSTALL_USER=
INSTALL_GROUP=

TAR_REPRODUCIBLE_ARGS=nonreproducible
GZIP_REPRODUCIBLE_ARGS=
SKIP_REPRODUCIBLE_PDF=1